import type { Participant } from "@/entities/user";

export const mockParticipants: Participant[] = [
  {
    id: "1",
    firstName: "Иван",
    lastName: "Иванов",
    role: "teacher",
    status: "active",
    avatarColor: "#b7bdff",
  },
  {
    id: "2",
    firstName: "Мария",
    lastName: "Петрова",
    role: "student",
    status: "active",
    avatarColor: "#b0e9fb",
  },
  {
    id: "3",
    firstName: "Алексей",
    lastName: "Сидоров",
    role: "student",
    status: "active",
    avatarColor: "#9cf38d",
  },
  {
    id: "4",
    firstName: "Елена",
    lastName: "Козлова",
    role: "student",
    status: "active",
    avatarColor: "#f2b2d6",
  },
  {
    id: "5",
    firstName: "Дмитрий",
    lastName: "Николаев",
    role: "student",
    status: "active",
    avatarColor: "#ffb8b8",
  },
  {
    id: "6",
    firstName: "Анна",
    lastName: "Михайлова",
    role: "student",
    status: "active",
    avatarColor: "#ffd4a3",
  },
  {
    id: "7",
    firstName: "Сергей",
    lastName: "Алексеев",
    role: "student",
    status: "active",
    avatarColor: "#d4b8ff",
  },
  {
    id: "8",
    firstName: "Ольга",
    lastName: "Васильева",
    role: "assistant",
    status: "active",
    avatarColor: "#b8ffd4",
  },
  {
    id: "9",
    firstName: "Павел",
    lastName: "Григорьев",
    role: "student",
    status: "active",
    avatarColor: "#ffc9e8",
  },
  {
    id: "10",
    firstName: "Татьяна",
    lastName: "Дмитриева",
    role: "student",
    status: "active",
    avatarColor: "#c9e8ff",
  },
  {
    id: "11",
    firstName: "Андрей",
    lastName: "Соколов",
    role: "student",
    status: "active",
    avatarColor: "#e8c9ff",
  },
  {
    id: "12",
    firstName: "Наталья",
    lastName: "Федорова",
    role: "student",
    status: "active",
    avatarColor: "#c9ffd4",
  },
  {
    id: "13",
    firstName: "Владимир",
    lastName: "Морозов",
    role: "student",
    status: "active",
    avatarColor: "#b7bdff",
  },
  {
    id: "14",
    firstName: "Екатерина",
    lastName: "Волкова",
    role: "student",
    status: "active",
    avatarColor: "#b0e9fb",
  },
  {
    id: "15",
    firstName: "Игорь",
    lastName: "Новиков",
    role: "student",
    status: "active",
    avatarColor: "#9cf38d",
  },
  {
    id: "16",
    firstName: "Светлана",
    lastName: "Павлова",
    role: "student",
    status: "active",
    avatarColor: "#f2b2d6",
  },
  {
    id: "17",
    firstName: "Максим",
    lastName: "Семенов",
    role: "student",
    status: "active",
    avatarColor: "#ffb8b8",
  },
  {
    id: "18",
    firstName: "Юлия",
    lastName: "Егорова",
    role: "student",
    status: "active",
    avatarColor: "#ffd4a3",
  },
  {
    id: "19",
    firstName: "Роман",
    lastName: "Кузнецов",
    role: "student",
    status: "active",
    avatarColor: "#d4b8ff",
  },
  {
    id: "20",
    firstName: "Виктория",
    lastName: "Попова",
    role: "student",
    status: "active",
    avatarColor: "#b8ffd4",
  },
  {
    id: "21",
    firstName: "Артем",
    lastName: "Лебедев",
    role: "student",
    status: "active",
    avatarColor: "#ffc9e8",
  },
  {
    id: "22",
    firstName: "Дарья",
    lastName: "Козлова",
    role: "student",
    status: "active",
    avatarColor: "#c9e8ff",
  },
  {
    id: "23",
    firstName: "Кирилл",
    lastName: "Степанов",
    role: "student",
    status: "active",
    avatarColor: "#e8c9ff",
  },
  {
    id: "24",
    firstName: "Алина",
    lastName: "Романова",
    role: "student",
    status: "inactive",
    avatarColor: "#c9ffd4",
  },
];
