import type { DemoSubmission } from "../model/types";

const demoSubmissions: DemoSubmission[] = [
  {
    id: "s1",
    assignmentId: "a1",
    studentId: "u1",
    studentName: "Иван Петров",
    content: "Лендинг готов, опубликован на Vercel",
    files: [],
    submittedAt: new Date("2025-02-10"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
  {
    id: "s2",
    assignmentId: "a1",
    studentId: "u10",
    studentName: "Анна Козлова",
    content: "Лендинг с анимациями на framer-motion",
    files: [],
    submittedAt: new Date("2025-02-11"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
  {
    id: "s3",
    assignmentId: "a1",
    studentId: "u11",
    studentName: "Никита Волков",
    content: "Адаптивный лендинг + dark mode",
    files: [],
    submittedAt: new Date("2025-02-12"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
  {
    id: "s4",
    assignmentId: "a1",
    studentId: "u12",
    studentName: "Елена Морозова",
    content: "Лендинг с интерактивными карточками",
    files: [],
    submittedAt: new Date("2025-02-12"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
  {
    id: "s5",
    assignmentId: "a1",
    studentId: "u13",
    studentName: "Дмитрий Фёдоров",
    content: "Минималистичный одностраничник",
    files: [],
    submittedAt: new Date("2025-02-13"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
  {
    id: "s6",
    assignmentId: "a1",
    studentId: "u14",
    studentName: "Ольга Белова",
    content: "Лендинг с CMS-подключением",
    files: [],
    submittedAt: new Date("2025-02-13"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
  // ── REST API submissions for assignment a2 ────────────────────────
  {
    id: "s7",
    assignmentId: "a2",
    studentId: "u15",
    studentName: "Павел Романов",
    content: "REST API на Express + Postgres",
    files: [],
    submittedAt: new Date("2025-02-28"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
  {
    id: "s8",
    assignmentId: "a2",
    studentId: "u16",
    studentName: "София Лебедева",
    content: "REST API на FastAPI с тестами",
    files: [],
    submittedAt: new Date("2025-02-28"),
    status: "submitted",
    studentMark: null,
    teacherMark: null,
  },
];

export const workRepo = {
  getAll: (): Promise<DemoSubmission[]> => Promise.resolve(demoSubmissions),
  listForHomework: (homeworkId: string): Promise<DemoSubmission[]> =>
    Promise.resolve(demoSubmissions.filter((s) => s.assignmentId === homeworkId)),
  getMineForHomework: (_homeworkId: string): Promise<DemoSubmission | null> =>
    Promise.resolve(null),
  getById: (submissionId: string): Promise<DemoSubmission | null> =>
    Promise.resolve(demoSubmissions.find((s) => s.id === submissionId) ?? null),
  create: (_homeworkId: string, _comment: string) =>
    Promise.resolve({ submissionId: `s${Date.now()}` }),
  update: (_submissionId: string, _comment: string) => Promise.resolve(),
  delete: (_submissionId: string) => Promise.resolve(),
  correctMark: (_submissionId: string, _mark: number) => Promise.resolve(),
};
